name: SoDA Lab
description: Software Design and Analysis Lab at Carnegie Mellon University
copyright: "SoDA Lab"
meta_description: "Software Design and Analysis Lab"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "http://cmu-soda.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# output destination
destination: ../../EXPORT-SODA-WEB

# Details for the RSS feed generator
url: "cmu-soda.github.io"
author: "SoDA Lab"
author_description: "Software Design and Analysis Lab"

# Disqus config
disqus-shortname: ""
